$schema: https://azuremlschemas.azureedge.net/latest/commandJob.schema.json
command: >-
 GIT_LFS_SKIP_SMUDGE=1 uv pip install -e . && 
 uv run scripts/train.py pi0_fast_custom 
 --exp-name=${{inputs.pi0_experiment_name}} 
 --assets-base-dir ${{outputs.ASSETS_BASE}} 
 --checkpoint-base-dir ${{outputs.MODEL_CHECKPOINTS}} 
 --num-train-steps ${{inputs.num_train_steps}}
 --num-workers 8 
 --fsdp-devices 1 
 --batch-size 32 
 --mlflow-enabled
 --no-wandb-enabled
 ${{inputs.extra_flags}}
environment: azureml:<env_name>:<env_version>
inputs:
  pi0_experiment_name: <pi0_exp_name>
  num_train_steps: 30000
  extra_flags: ';'
outputs:
  MODEL_CHECKPOINTS:
    type: uri_folder
    path: azureml://datastores/<ds_name>/paths/finetuned_model/
  HF_LEROBOT_HOME:
    type: uri_folder
    path: azureml://datastores/<ds_name>/paths/pi0_fast_custom
  ASSETS_BASE:
    type: uri_folder
    path: azureml://datastores/<ds_name>/paths/
environment_variables:
  HF_LEROBOT_HOME: ${{outputs.HF_LEROBOT_HOME}}
  MODEL_CHECKPOINTS: ${{outputs.MODEL_CHECKPOINTS}}
  XLA_PYTHON_CLIENT_PREALLOCATE: "false"
  XLA_PYTHON_CLIENT_MEM_FRACTION: ".95"
  XLA_PYTHON_CLIENT_ALLOCATOR: "platform"
display_name: p0_libero_finetune
experiment_name: p0_libero_finetune
compute: <gpu_vm_name>
code: ../..